_wandb:
    value:
        cli_version: 0.24.2
        e:
            b8gi63xx4c5f2c9dxrbh1e3o1od7a93t:
                apple:
                    ecpuCores: 2
                    gpuCores: 14
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "26843545600"
                codePath: /Users/juli/Documents/cs/machine learning/GNNs/cayleydoscope/cayleydoscope/clrs/examples/experiments.ipynb
                codePathLocal: experiments.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "374047571968"
                email: crayolaskiesforathousandmiles@gmail.com
                executable: /Users/juli/Documents/cs/machine learning/GNNs/cayleydoscope/cayleydoscope/cayleydoscope/bin/python
                git:
                    commit: f13a1b0a48347c144d3984dfdd007fc5dc55607a
                    remote: git@github.com:tgoab/cayleydoscope.git
                host: Julis-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/juli/Documents/cs/machine learning/GNNs/cayleydoscope/cayleydoscope/clrs/examples/experiments.ipynb
                python: CPython 3.12.11
                root: /Users/juli/Documents/cs/machine learning/GNNs/cayleydoscope/cayleydoscope/clrs/examples
                startedAt: "2026-02-11T17:25:05.915051Z"
                writerId: b8gi63xx4c5f2c9dxrbh1e3o1od7a93t
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 2
                - 3
                - 12
            "2":
                - 2
                - 3
                - 12
            "3":
                - 2
                - 13
            "4": 3.12.11
            "5": 0.24.2
            "8":
                - 1
            "12": 0.24.2
            "13": darwin-arm64
